name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Start Asolo deploying
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="🚀 Asolo deploy starting (ветка *${{ github.ref_name }}*)"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 20m
          script_stop: true
          script: |
            set -e

            DEPLOY_PATH="/var/www/asolo"

            cd "$DEPLOY_PATH"
            git config --global --add safe.directory "$DEPLOY_PATH"
            git pull --ff-only origin main

            composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction
            npm ci
            npm run build

            php artisan optimize:clear
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

      - name: deploy finished
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="✅ deploy finished successfully for *${{ github.repository }}* on branch *${{ github.ref_name }}*"

      - name: Deploy failed
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="❌ Deploy Error *${{ github.repository }}* on branch *${{ github.ref_name }}*. Check pipeline: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
