name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
#      - name: Checkout code (only needed to avoid errors in workflow)
#        uses: actions/checkout@v4
#
#      - name: Set up PHP (optional, not used in remote deploy)
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: 8.3
#          extensions: mbstring, xml, bcmath, zip, curl
#          tools: composer

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/acode || exit 1
            git pull origin main || exit 1
            composer install --no-dev --optimize-autoloader || exit 1
            php artisan migrate --force || exit 1
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
